spring.datasource.url= jdbc:postgresql://expense_tracker_db_4hyz_user:dCb1MgulgyFPi36bWT5xwfgEUXIjQPMq@dpg-d6u41c0gjchc73cpt840-a/expense_tracker_db_4hyz
spring.datasource.username= expense_tracker_db_4hyz_user
spring.datasource.password= dCb1MgulgyFPi36bWT5xwfgEUXIjQPMq

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080